import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className="w-full h-full" lang="en">
            <body className="w-full h-full min-h-screen dark:bg-zinc-900 bg-zinc-50 dark:text-zinc-50 text-zinc-900">
                <main className="px-5 sm:px-0 max-w-3xl mx-auto w-full h-full flex flex-col gap-3 justify-center items-center">
                    {children}
                </main>
            </body>
        </html>
    );
}
